var quotes = [
    'It does not matter how slowly you go as long as you do not stop.<br><br>Confucius',
    'Wherever you go, go with all your heart.<br><br>Confucius',
    'Every day is a journey, and the journey itself is home.<br><br>Matsuo Basho',
    'A good traveler has no fixed plans, and is not intent on arriving.<br><br>Lao Tzu',
    'The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty.<br><br>Winston Churchill',
    'Don\'t let yesterday take up too much of today.<br><br>Will Rodgers',
    'It\'s not whether you get knocked down, it\'s whether you get up.<br><br>Vince Lombardi',
    'If you are working on something exciting that you really care about, you don\'t have to be pushed. The vision pulls you.<br><br>Steve Jobs',
    'Whether you think you can or think you can\'t, you\'re right.<br><br>Henry Ford',
    'The only limit to our realization of tomorrow will be our doubts of today.<br><br>Franklin D. Roosevelet',
    'Creativity is intelligence having fun.<br><br>Albert Einstein',
    'You are never too old to set another goal or to dream a new dream.<br><br>C.S. Lewis',
    'Today\'s accomplishments were yesterday\'s impossibilities.<br><br>Robert H. Schuller',
    'If you haven\'t found it yet, keep looking. Don\'t settle.<br><br>Steve Jobs',
    'Perpetual optimisim is a force multiplier.<br><br>Colin Powell',
    'Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.<br><br>Arnold Schwarzenegger',
    'The world breaks everyone, and afterward, some are strong at the broken places.<br><br>Ernest Hemingway',
    'All the adversity I’ve had in my life, all my troubles and obstacles, have strengthened me. You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you.<br><br>Walt Disney',
    'A truly strong person does not need the approval of others any more than a lion needs the approval of sheep.<br><br>Vernon Howard',
    'There are better starters than me, but I’m a strong finisher.<br><br>Usain Bolt',
    'He who believes is strong; he who doubts is weak. Strong convictions precede great actions.<br><br>Louisa May Alcott',
    'Strength and growth come only through continuous effort and struggle.<br><br>Napoleon Hill',
    'Make up your mind that no matter what comes your way, no matter how difficult, no matter how unfair, you will do more than simply survive. You will thrive in spite of it.<br><br>Joel Osteen',
    'Tough times never last, but tough people do.<br><br>Robert H. Schuller',
    'I believe that tomorrow is another day.<br><br>Audrey Hepburn',
    'That which does not kill us makes us stronger.<br><br>Friedrich Nietzsche',
    'If you are not willing to risk the usual you will have to settle for the ordinary.<br><br>Jim Rohn',
    'All our dreams can come true if we have the courage to pursue them.<br><br>Walt Disney',
    'Success is walking from failure to failure with no loss of enthusiasm.<br><br>Winston Churchill',
    'Opportunities don’t happen, you create them.<br><br>Chris Grosser',
    'Try not to become a person of success, but rather try to become a person of value.<br><br>Albert Einstein',
    'Great minds discuss ideas; average minds discuss events; small minds discuss people.<br><br>Eleanor Roosevelt',
    'No one can make you feel inferior without your consent.<br><br>Eleanor Roosevelt',
    'If you’re going through hell keep going.<br><br>Winston Churchill',
    'What seems to us as bitter trials are often blessings in disguise.<br><br>Oscar Wilde',
    'The distance between insanity and genius is measured only by success<br><br>Bruce Feirstein',
    'Don\’t be afraid to give up the good to go for the great.<br><br>John D. Rockefeller',
    'Life is not about finding yourself. Life is about creating yourself.<br><br>Lolly Daskal',
    'Innovation distinguishes between a leader and a follower.<br><br>Steve Jobs',
    'There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.<br><br>Ray Goforth',
    'The starting point of all achievement is desire.<br><br>Napolean Hill',
    'Courage is resistance to fear, mastery of fear - not absense of fear.<br><br>Mark Twain',
    'A real entrepreneur is somebody who has no safety net underneath them.<br><br>Henry Kravis',
    'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.<br><br>Mark Caine',
    'Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.<br><br>Dale Carnegie',
    'Don’t let the fear of losing be greater than the excitement of winning.<br><br>Robert Kiyosaki',
    'To accomplish great things, we must not only act, but also dream, not only plan, but also believe.<br><br>Anatole France',
    'It is better to fail in originality than to succeed in imitation.<br><br>Herman Melville',
    'Little minds are tamed and subdued by misfortune; but great minds rise above it.<br><br>'
];

function newQuote(){
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteD').innerHTML = quotes[randomNumber];
}

